apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  completions: 100
  parallelism: 4
  template:
    metadata:
      name: demo-job
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl"]
        args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
