apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ingress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-ingress
      version: v1
  template:
    metadata:
      labels:
        app: demo-ingress
        version: v1
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello-world
        ports:
        - containerPort: 8080
