apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-secret
spec:
  selector:
    matchLabels:
      app: demo-secret
  template:
    metadata:
      labels:
        app: demo-secret
    spec:
      containers:
      - name: hello-world
        image: gcr.io/google-samples/node-hello:1.0
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: demo-secret-manifest
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret-manifest
              key: password             
      volumes:
      - name: secrets
        secret:
          secretName: demo-secret-file
