apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-02-13T09:13:56Z"
  generateName: demo-redis-master-596696dd4-
  labels:
    app: redis
    pod-template-hash: 596696dd4
    role: master
    tier: backend
  name: demo-redis-master-596696dd4-zdg9b
  namespace: lab-guestbook
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: demo-redis-master-596696dd4
    uid: 298ce6dc-4e41-11ea-b1d4-42010a840138
  resourceVersion: "296624"
  selfLink: /api/v1/namespaces/lab-guestbook/pods/demo-redis-master-596696dd4-zdg9b
  uid: 29926a29-4e41-11ea-b1d4-42010a840138
spec:
  containers:
  - image: k8s.gcr.io/redis:e2e
    imagePullPolicy: IfNotPresent
    name: master
    ports:
    - containerPort: 6379
      protocol: TCP
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-z929h
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-lab-cluster-default-pool-0da17cf9-701h
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-z929h
    secret:
      defaultMode: 420
      secretName: default-token-z929h
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-13T09:13:56Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-02-13T09:14:16Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-13T09:14:16Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-13T09:13:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://d0075f6cf1612636e16cea6e2cc7639dd3e9d343e1f4852a3459ee9889391d9c
    image: k8s.gcr.io/redis:e2e
    imageID: docker-pullable://k8s.gcr.io/redis@sha256:f066bcf26497fbc55b9bf0769cb13a35c0afa2aa42e737cc46b7fb04b23a2f25
    lastState: {}
    name: master
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-02-13T09:14:16Z"
  hostIP: 10.132.0.11
  phase: Running
  podIP: 10.48.2.20
  qosClass: Burstable
  startTime: "2020-02-13T09:13:56Z"
