apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-burstable
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
