apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-challenge
spec:
  containers:
  - name: qos-demo-ctr-1
    image: nginx
    resources:
      requests:
        memory: "200Mi"
  - name: qos-demo-ctr-2
    image: redis
